name: PubMLST Scan

on:
  schedule:
    - cron: '0 0 * * 3'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install jq

      - name: Run PubMLST Deep Scan
        id: scan
        run: |
          chmod +x ./assets/check_pubmlst.sh
          ./assets/check_pubmlst.sh > scan_report.txt
          
          TRACKED_COUNT=$(tail -n +2 known_schemes.csv | wc -l)
          echo "TRACKED_COUNT=$TRACKED_COUNT" >> $GITHUB_ENV
          
          if grep -qE "\+ NEW|\- REMOVED" scan_report.txt; then
            echo "DISCREPANCY=true" >> $GITHUB_ENV
            
            # This 'heredoc' marker (EOF) is required for multi-line text
            echo "REPORT_BODY<<EOF" >> $GITHUB_ENV
            sed -n '/DISCREPANCY REPORT/,$p' scan_report.txt >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "DISCREPANCY=false" >> $GITHUB_ENV
          fi

      - name: Update Tracked Count Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: ${{ secrets.GIST_ID }}
          filename: pubmlst_schemes.json
          label: PubMLST Schemes
          message: ${{ env.TRACKED_COUNT }}
          color: "002147"

      - name: Send Email Report
        if: env.DISCREPANCY == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "⚠️ PubMLST Discrepancy Detected"
          to: marian.freisleben@liora-bioinformatics.com
          from: GitHub Actions Monitor
          body: |
            The weekly PubMLST scan has detected changes.
            Tracked Schemes: ${{ env.TRACKED_COUNT }}
            
            ${{ env.REPORT_BODY }}
